# Generated by Django 5.2 on 2025-05-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='email',
            field=models.EmailField(default='msm875990@gmail.com', max_length=254),
        ),
    ]
