# Generated by Django 5.2 on 2025-05-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_webpage_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
