# Generated by Django 5.2 on 2025-05-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_accessrecord_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrecord',
            name='price',
            field=models.IntegerField(),
        ),
    ]
