# Generated by Django 5.2 on 2025-05-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_accessrecord_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrecord',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
