# Generated by Django 5.2 on 2025-05-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_accessrecord_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrecord',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
